
#mom1_1km('/Users/akankshabij/Documents/MSc/Research/Data/Mopra/HNC_3mm_Vela_C_T_MB.fits', bmap_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_integratedIntensity12CO.fits', folder='Output_Plots/BandC/Mopra/Cube/', start=-5, end=15, index=0, incr=0.1, pdfName='', gifName='', project=True, band=0, projMap=None, colDen='/Users/akankshabij/Documents/MSc/Research/Data/Herschel/HighresNmap_herschel_velac_high_av.fits')

#ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CS_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CS/', project=False, start=0, end=13, pdfName='13CS_mom0_cube_ALMAband6.pdf', gifName='N2D_mom0_cube_ALMAband6.gif', band=0)
# ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/CO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/CO/', project=False, start=0, end=13, pdfName='CO_mom0_cube_ALMAband6.pdf', gifName='CO_mom0_cube_ALMAband6.gif', band=0)
# ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/SiO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/SiO/', project=False, start=0, end=13, pdfName='SiO_mom0_cube_ALMAband6.pdf', gifName='SiO_mom0_cube_ALMAband6.gif', band=0)
# ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/C18O_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/C18O/', project=False, start=0, end=13, pdfName='C18O_mom0_cube_ALMAband6.pdf', gifName='C18O_mom0_cube_ALMAband6.gif', band=0)
# ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/H2CO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/H2CO/', project=False, start=0, end=13, pdfName='H2CO_mom0_cube_ALMAband6.pdf', gifName='H2CO_mom0_cube_ALMAband6.gif', band=0)
# ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CN_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CN/', project=False, start=0, end=13, pdfName='13CN_mom0_cube_ALMAband6.pdf', gifName='13CN_mom0_cube_ALMAband6.gif', band=0)
# ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/N2D_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/N2D/', project=False, start=-3, end=3, pdfName='N2D_mom0_cube_ALMAband6.pdf', gifName='N2D_mom0_cube_ALMAband6.gif', band=0)

#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/SiO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/SiO/', project=False, start=0, end=13, pdfName='mom0_cube_ALMASiO_contoursACA.pdf', gifName='mom0_cube_ALMASiO_contoursACA.gif')
#runAnalysis(HAWC, outName='HAWC_polI/', Mask=None, label='HAWC+ Band C Polarized I', index=13, project=False, band=0, highRes=False, kstep=2)
#runAnalysis(HAWE, outName='HAWE_polI/', Mask=None, label='HAWC+ Band E Polarized I', index=13, project=False, band=1, highRes=False, kstep=2)

#plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/C18O/')
#plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/13CN/')
#plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/13CN/')
#plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/13CS/')
#binHerschel()
#runCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', 0)
#gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/SiO/', 'DataMask.pdf', 'DataMask.gif')
#gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/C18O/', 'hist.pdf', 'hist.gif')
#runAll()
#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', 0, '13CO_Map.pdf', '13CO_Map.gif', folder='Output_Plots/BandC/13CO/Cube/')

#plotCube('/Users/akankshabij/Document2s/MSc/Research/Data/CO_LarsBonne/CII/07_0077_RCW36_CII_L.fits', folder='Output_Plots/BandE/CII/Cube/', project=True, start=-5, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=1)
#calcNoise(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CII/07_0077_RCW36_CII_L.fits', fldr='Output_Plots/BLASTpol/CII/Cube/', start=17, end=22, project=False)
#runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CII/07_0077_RCW36_CII_L.fits', folder='Output_Plots/BandC/CII/Cube/', out='CII/Cube/', start=-1, end=16, project=True, highRes=False, band=0)
#gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BLASTpol/CII/Cube/')
#plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/CII/Cube/')
#plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BLASTpol/CII/Cube/')
# plotPRS_Bands('CII/')
# plotPRS_Bands('12CO/')
# plotPRS_Bands('13CO/')
# plotPRS_Bands('Mopra/')
#totalHIST('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/CII/Cube/')

#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_12CO32.fits', folder='Output_Plots/BandE/12CO/Cube/', project=True, start=-3, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=1)
# plotCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/O/RCW36_OI_30_15.fits', folder='Output_Plots/BandC/OI/Cube/', project=True, start=-3, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=0)
# plotCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/O/RCW36_OI_30_15.fits', folder='Output_Plots/BLASTpol/OI/Cube/', project=False, start=-3, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=2)
# plotCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/O/RCW36_OI_30_15.fits', folder='Output_Plots/BandE/OI/Cube/', project=True, start=-3, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=1)
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_12CO32.fits', folder='Output_Plots/BandC/12CO/Cube/', project=True, start=-3, end=17, pdfName='12CO_mom0_cube_1kms.pdf', gifName='12CO_mom0_cube_1kms.gif', band=0)
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', folder='Output_Plots/BandC/13CO/Cube/', project=True, start=-3, end=17, pdfName='13CO_mom0_cube_1kms.pdf', gifName='13CO_mom0_cube_1kms.gif', band=0)
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CII/07_0077_RCW36_CII_L.fits', folder='Output_Plots/BandC/CII/Cube/', project=True, start=-3, end=17, pdfName='CII_mom0_cube_1kms.pdf', gifName='CII_mom0_cube_kms.gif', band=0)
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CS_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CS/', project=False, start=0, end=13, pdfName='mom0_cube_ALMA13CS.pdf', gifName='mom0_cube_ALMA13CS.gif')
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/CO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/CO/', project=False, start=0, end=13, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif')
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/SiO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/SiO/', project=False, start=0, end=13, pdfName='mom0_cube_ALMASiO.pdf', gifName='mom0_cube_ALMASiO.gif')
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/C18O_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/C18O/', project=False, start=0, end=13, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif')
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/H2CO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/H2CO/', project=False, start=0, end=13, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif')
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CN_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CN/', project=False, start=0, end=13, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif')
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/N2D_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/N2D/', project=False, start=-3, end=3, pdfName='mom0_cube_ALMA.pdf', gifName='mom0_cube_ALMA.gif')
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', folder='Output_Plots/BandC/13CO/Cube/', project=True, start=-3, end=17, pdfName='13CO_mom0_cube_1kms.pdf', gifName='13CO_mom0_cube_kms.gif', band=0)
# mom0_1km('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CII/07_0077_RCW36_CII_L.fits', folder='Output_Plots/BandC/CII/Cube/', project=True, start=-3, end=17, pdfName='CII_mom0_cube_1kms.pdf', gifName='CII_mom0_cube_kms.gif', band=0)

#ALMACont('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', folder='Output_Plots/BandC/13CO/Cube/', project=True, start=-3, end=17, pdfName='13CO_mom0_ALMA13CS.pdf', gifName='13CO_mom0_ALMA13CS.gif', band=0)
# calcNoise(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_12CO32.fits', fldr='Output_Plots/BandE/12CO/Cube/', start=-3, end=-1, project=True, band=1)
#runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_12CO32.fits', folder='Output_Plots/BandC/12CO/Cube/', out='12CO/Cube/', start=-2, end=17, project=True, highRes=False, band=0)
#gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/12CO/Cube/')
#plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/12CO/Cube/')
#plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/12CO/Cube/')
#totalHIST('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/12CO/Cube/')

#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', folder='Output_Plots/BandE/13CO/Cube/', project=True, start=-3, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=1)
# calcNoise(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', fldr='Output_Plots/BLASTpol/13CO/Cube/', start=-3, end=0, project=False)
# runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', folder='Output_Plots/BLASTpol/13CO/Cube/', out='13CO/Cube/', start=-2, end=17, project=False, highRes=False, band=2)
# gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BLASTpol/13CO/Cube/')
# plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BLASTpol/13CO/Cube/')
# plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BLASTpol/13CO/Cube/')

# plotCube('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', folder='Output_Plots/BandC/13CO/Cube/', project=True, start=-3, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=0)
# calcNoise(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', fldr='Output_Plots/BandC/13CO/Cube/', start=-3, end=0, project=True, band=0)
# runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', folder='Output_Plots/BandC/13CO/Cube/', out='13CO/Cube/', start=-2, end=17, project=True, highRes=False, band=0)
# gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/13CO/Cube/')
# plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/13CO/Cube/')
# plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/13CO/Cube/')
# totalHIST('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/13CO/Cube/')

# plotCube('/Users/akankshabij/Documents/MSc/Research/Data/Mopra/HNC_3mm_Vela_C_T_MB.fits', folder='Output_Plots/BandC/Mopra/Cube/', project=True, start=-3, end=17, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif', band=0)
# calcNoise(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/Mopra/HNC_3mm_Vela_C_T_MB.fits', fldr='Output_Plots/BandC/Mopra/Cube/', start=-3, end=-1, project=True, band=0)
# runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/Mopra/HNC_3mm_Vela_C_T_MB.fits', folder='Output_Plots/BandC/Mopra/Cube/', out='Mopra/Cube/', start=-2, end=17, project=True, highRes=False, band=0)
# gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/Mopra/Cube/')
# plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/Mopra/Cube/')
# plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/Mopra/Cube/')
# totalHIST('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/Mopra/Cube/')

# runMaskCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CN_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CN/', out='ALMA/cubes/13CN/', regions=[[150, 70], [40, 100], [180, 380], [230, 200]], start=0, end=13, project=False, highRes=True, band=0)
# gifCube(fldr='Output_Plots/BandC/ALMA/cubes/13CN/')
# plotPRS_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/13CN/')
# plotHIST_speed('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/13CN/')
# totalHIST('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/13CN/')
#runAnalysis(fits_fl='Data/Observations/CII_Integrated.fits', outName='CII/', index=0, project=False, kernel='Gaussian', kstep=3, isSim=False, band=2, highRes=False, file=True, Map=None, BinMap=None)
#runAnalysis(Bmap=Bmap.data, outName=fldr+'/', Mask=Mask, vecMask=Mask, label=label, index=index, project=False, kernel='Gaussian', kstep=2, isSim=False, band=band, highRes=highRes, file=False, Map=mom0_HAWC)
#runAnalysis(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CII/CII_Tex.fits', outName='CII_Tex/', index=0, project=False, kernel='Gaussian', kstep=2, isSim=False, band=0, highRes=False, file=True, Map=None, BinMap=None)
#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/CO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/CO/', project=False, start=0, end=13, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif')
#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/H2CO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/H2CO/', project=False, start=0, end=13, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif')
#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CN_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CN/', project=False, start=0, end=13, pdfName='mom0_cube.pdf', gifName='mom0_cube.gif')
#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/N2D_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/N2D/', project=False, start=-3, end=3, pdfName='mom0_cube_ALMA.pdf', gifName='mom0_cube_ALMA.gif')
#plotCube('/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CS_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CS/', project=False, start=0, end=13, pdfName='mom0_cube_ALMA.pdf', gifName='mom0_cube_ALMA.gif')
#runMaskCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/ALMA/N2D_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/N2D/', out='ALMA/cubes/N2D/', regions=[[150, 70], [40, 100], [180, 380], [230, 200]], start=-3, end=3, project=False, highRes=True, band=0)
# gifCube(fldr='Output_Plots/BandC/ALMA/cubes/N2D/')
# plotPRS_speed('Output_Plots/BandC/ALMA/cubes/N2D/')
# plotHIST_speed('Output_Plots/BandC/ALMA/cubes/N2D/')
# totalHIST('Output_Plots/BandC/ALMA/cubes/N2D/')
#calcNoise(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/ALMA/CO_Cube.fits', fldr='Output_Plots/BandC/ALMA/cubes/CO/', start=-9, end=-7)
#calcNoise(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/ALMA/C18O_Cube.fits', fldr='Output_Plots/BandC/ALMA/cubes/C18O/', start=0, end=2)
#runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/ALMA/SiO_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/SiO/', out='ALMA/cubes/SiO/', start=0, end=13)
#gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/SiO/')
#runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/ALMA/C18O_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/C18O/', out='ALMA/cubes/C18O/', start=0, end=13)
#runCube(fits_fl='/Users/akankshabij/Documents/MSc/Research/Data/ALMA/13CN_Cube.fits', folder='Output_Plots/BandC/ALMA/cubes/13CN/', out='ALMA/cubes/13CN/', start=0, end=13)
#gifCube('/Users/akankshabij/Documents/MSc/Research/Code/scripts/HRO/HRO_BijA/Output_Plots/BandC/ALMA/cubes/13CN/')
#runBinHersch()
#calcNoise('/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_13CO32.fits', 0, fldr='Output_Plots/BandC/13CO/Cube/', start=-1, end=2)
#runChannelMaps(fl='/Users/akankshabij/Documents/MSc/Research/Data/CO_LarsBonne/CO/RCW36_12CO32.fits', fldr='12CO/')
#runNoise('Data/Observations/Herschel_ColumnDensity.fits', outName='ColumnDensity/', label='Herschel Column Density', index=1, project=True, kernel='Gaussian', kstep=5, isSim=False, band=0, highRes=False)

# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/colDen.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/Temp.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/Hersh_70.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/Hersh_160.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/Hersh_250.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/Hersh_350.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/Hersh_500.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Cutouts/Hersh_160.fits', index=0, outName='ColumnDensity/', counter=10, label='Herschel Column Density', kstep=3)
# loopNoise('Data/Observations/Hershel_Temperature.fits', outName='Temperature/', counter=10, label='Herschel Temperature', kstep=5)
# loopNoise('Data/Observations/12CO_Integrated.fits', outName='12CO/', counter=10, label='12CO', kstep=2)
# loopNoise('Data/Observations/13CO_Integrated.fits', outName='13CO/', counter=10, label='13CO', kstep=2)
# loopNoise('Data/Observations/CII_Integrated.fits',  outName='CII/',  counter=10, label='CII',  kstep=2)
# loopNoise('Data/Observations/ALMA_Band6_continuum.fits', outName='ALMA/', counter=10, label='ALMA Band 6 Continuum', kstep=1)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Mopra/Integrated_mom0_0to12kmpers.fits', outName='Mopra/', counter=10, label='Mopra HNC', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Herschel/HighresNmap_herschel_velac_high_av.fits', outName='Highres_ColumnDensity/', counter=10, label='Highres Herschel Column Density', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Herschel/HighresTmap_velac_temperature_cf_r500_medsmo3.fits', outName='Highres_Temperature/', counter=10, label='Highres Herschel Temperature', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/HAWC/Rereduced_2018-07-14_HA_F487_004-065_POL_70060957_HAWC_HWPC_PMP.fits', outName='HAWC_BandC/', counter=10, label='HAWC Band C Intensity', kstep=1)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/HAWC/Rereduced_2018-07-14_HA_F487_031-040_POL_70060912_HAWE_HWPE_PMP.fits', outName='HAWC_BandE/', counter=10, label='HAWC Band E Intensity', kstep=1)

# loopNoise('Data/Observations/Herschel_ColumnDensity.fits', outName='ColumnDensity/', counter=100, label='Herschel Column Density', index=1, kstep=5)
# loopNoise('Data/Observations/Hershel_Temperature.fits', outName='Temperature/', counter=100, label='Herschel Temperature', kstep=5)
# loopNoise('Data/Observations/12CO_Integrated.fits', outName='12CO/', counter=100, label='12CO', kstep=2)
# loopNoise('Data/Observations/13CO_Integrated.fits', outName='13CO/', counter=100, label='13CO', kstep=2)
# loopNoise('Data/Observations/CII_Integrated.fits',  outName='CII/',  counter=100, label='CII',  kstep=2)
# loopNoise('Data/Observations/ALMA_Band6_continuum.fits', outName='ALMA/', counter=100, label='ALMA Band 6 Continuum', kstep=1)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Mopra/Integrated_mom0_0to12kmpers.fits', outName='Mopra/', counter=100, label='Mopra HNC', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Herschel/HighresNmap_herschel_velac_high_av.fits', outName='Highres_ColumnDensity/', counter=100, label='Highres Herschel Column Density', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Herschel/HighresTmap_velac_temperature_cf_r500_medsmo3.fits', outName='Highres_Temperature/', counter=100, label='Highres Herschel Temperature', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/HAWC/Rereduced_2018-07-14_HA_F487_004-065_POL_70060957_HAWC_HWPC_PMP.fits', outName='HAWC_BandC/', counter=100, label='HAWC Band C Intensity', kstep=1)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/HAWC/Rereduced_2018-07-14_HA_F487_031-040_POL_70060912_HAWE_HWPE_PMP.fits', outName='HAWC_BandE/', counter=100, label='HAWC Band E Intensity', kstep=1)

# loopNoise('Data/Observations/Herschel_ColumnDensity.fits', outName='ColumnDensity/', counter=1000, label='Herschel Column Density', index=1, kstep=5)
# loopNoise('Data/Observations/Hershel_Temperature.fits', outName='Temperature/', counter=1000, label='Herschel Temperature', kstep=5)
# loopNoise('Data/Observations/12CO_Integrated.fits', outName='12CO/', counter=1000, label='12CO', kstep=2)
# loopNoise('Data/Observations/13CO_Integrated.fits', outName='13CO/', counter=1000, label='13CO', kstep=2)
# loopNoise('Data/Observations/CII_Integrated.fits',  outName='CII/',  counter=1000, label='CII',  kstep=2)
# loopNoise('Data/Observations/ALMA_Band6_continuum.fits', outName='ALMA/', counter=1000, label='ALMA Band 6 Continuum', kstep=1)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Mopra/Integrated_mom0_0to12kmpers.fits', outName='Mopra/', counter=1000, label='Mopra HNC', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Herschel/HighresNmap_herschel_velac_high_av.fits', outName='Highres_ColumnDensity/', counter=1000, label='Highres Herschel Column Density', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/Herschel/HighresTmap_velac_temperature_cf_r500_medsmo3.fits', outName='Highres_Temperature/', counter=1000, label='Highres Herschel Temperature', kstep=5)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/HAWC/Rereduced_2018-07-14_HA_F487_004-065_POL_70060957_HAWC_HWPC_PMP.fits', outName='HAWC_BandC/', counter=1000, label='HAWC Band C Intensity', kstep=1)
# loopNoise('/Users/akankshabij/Documents/MSc/Research/Data/HAWC/Rereduced_2018-07-14_HA_F487_031-040_POL_70060912_HAWE_HWPE_PMP.fits', outName='HAWC_BandE/', counter=1000, label='HAWC Band E Intensity', kstep=1)

# WhiteNoise_PRS(outName='ColumnDensity/', counter=1000)
# WhiteNoise_PRS(outName='Temperature/', counter=1000)
# WhiteNoise_PRS(outName='12CO/', counter=1000)
# WhiteNoise_PRS(outName='13CO/', counter=1000)
# WhiteNoise_PRS(outName='CII/', counter=1000)
# WhiteNoise_PRS(outName='ALMA/', counter=1000)
# WhiteNoise_PRS(outName='Mopra/', counter=1000)
# WhiteNoise_PRS(outName='Highres_ColumnDensity/', counter=1000)
# WhiteNoise_PRS(outName='Highres_Temperature/', counter=1000)
# WhiteNoise_PRS(outName='HAWC_BandC/', counter=1000)
# WhiteNoise_PRS(outName='HAWC_BandE/', counter=1000)

# HAWC = fits.open('/Users/akankshabij/Documents/MSc/Research/Data/HAWC/Rereduced_2018-07-14_HA_F487_004-065_POL_70060957_HAWC_HWPC_PMP.fits')
# Nmap = 'Data/Observations/Herschel_ColumnDensity.fits'
# WhiteNoiseMap(Nmap, 1, HAWC[0], 'Output_Plots/WhiteNoise/ColumnDensity/')
#Load in simulation data
# Athena = fits.open('Data/Simulations/StrongBField/L1M10_Q.fits')
# Athena_mask = Athena[0].copy()
# Athena_mask.data = np.ones(Athena_mask.shape)
# Athena_col = fits.open('Data/Simulations/StrongBField/L1M10_colN.fits')[0]
# Qmap = (Athena[0]).data
# Umap = (fits.open('Data/Simulations/StrongBField/L1M10_U.fits')[0]).data
# hro = h.HRO(Athena_col.data, Qmap, Umap, hdu=Athena_mask, vecMask=Athena_mask, msk=True)   
# prefix = 'Output_Plots/BandC/Athena/StrongBField/'
# makePlots(hro, prefix, isSim=True, label='')
#Athena_StrongB = runAnalysis('Data/Simulations/StrongBField/L1M10_colN.fits',  outName='Athena/StrongBField/', project=False, Mask=Athena_mask, isSim=True, label='Athena - Strong Field')  

# Qmap = (fits.open('Data/Simulations/SuperAlfvenic/L10_Q.fits')[0]).data
# Umap = (fits.open('Data/Simulations/SuperAlfvenic/L10_U.fits')[0]).data
# Athena_SuperAlf = runAnalysis('Data/Simulations/SuperAlfvenic/L10_colN.fits',  prefix='Output_Plots/Athena/SuperAlfvenic/', project=False, Mask=Athena_mask, isSim=True, label='Athena - Super Alfvenic')  